#端口
server:
  port: 8085
  
#mysql jdbc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_beifen
    username: root
    password: root
    
    

logging:
  #控制台打印sql语句
  level:
    hello.test.dao: debug

