
#端口 
#mysql jdbc



spring:
  #配置文件环境
  profiles:
    active: prod
  #druid配置
  datasource: 
    druid:
      #监控范围
      aop-patterns: hello.test.*
      stat-view-servlet:
        login-username: admin
        login-password: 123
  
#mybatis加载
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: hello.test.entity
  #下划线转驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    
logging: 
  #加载日志文件
  config: classpath:logback-springboot.xml    
