#端口
server:
  port: 8082
  
#mysql jdbc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_beifen
    username: root
    password: root
    
    
#控制台打印sql语句
logging:
  level:
    hello.test.dao: debug
