#端口
server:
  port: 8082
  
#mysql jdbc
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.135.155:3307/auth_dev
    username: dev_auth
    password: 1qaz@WSX
    
    

logging:
  #控制台打印sql语句
  level:
    com.yaic.auth.thirdParty.dao: debug
    com.yaic.auth.interior.dao: debug
    

